# yaml-language-server: $schema=https://schema.blue-build.org/module-list-v1.json
---
# Final system configuration - services, targets

modules:
  - type: systemd
    system:
      enabled:
        # Core services
        - sshd
        - NetworkManager
        - bluetooth
        - firewalld
        
        # Cockpit
        - cockpit.socket
        
        # Power & thermal
        - power-profiles-daemon
        - acpid
        
        # Tuned performance profiles
        - tuned
      
      # Disable things we don't need
      disabled:
        - kdump
